# Generated by Django 5.0.6 on 2026-08-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=50)),
                ('letras_usadas', models.CharField(blank=True, default='', max_length=100)),
                ('intentos_restantes', models.IntegerField(default=6)),
                ('terminada', models.BooleanField(default=False)),
                ('ganada', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
